settings:
  title: ''
  url: 'https://status.muzza.cloud' # used for Slack messages
  logo: logo-muzza-2000.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-muzza-cz # unique identifier
    name: www.muzza.cz
    description: 'Czechia' # default=empty
    url: 'https://www.muzza.cz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: cz-muzza-dev
    name: cz.muzza.dev
    url: 'https://cz.muzza.dev'
    method: GET
    expectStatus: 401
    followRedirect: true # should fetch follow redirects, default=false

  - id: sk-muzza-dev
    name: sk.muzza.dev
    url: 'https://sk.muzza.dev'
    method: GET
    expectStatus: 401
    followRedirect: true # should fetch follow redirects, default=false

  - id: migration-muzza-design
    name: Migration
    url: 'https://migration.muzza.design'
    method: GET
    expectStatus: 401
    followRedirect: true # should fetch follow redirects, default=false
